### ISSUE TITLE
Problem in updating fuel composition for OpenMC calculation in successive iterations

### ISSUE THREAD

**Issue by khurrumsaleem** [bright-dev/xsgen#12]
Hi!

I have been using xsgen and after a very painstaking effort, i was able to make it run. But now, i think, there is a bug in the code. The fuel composition, which should be updated in each transport calculation being performed by OpenMC, doesn't change. It remains fixed as the starting composition of the fuel. 

ctx['_fuel_nucs'] = _mat_to_nucs(rc.fuel_material[valid_nucs])

rc.fuel_material is never updated. it is the same for each iteration and hence causing the bug, i think. Can you please take a look at this.

**Comment by scopatz** [comment]
Hi @khurrumsaleem - hmm I thought that I had fixed that issue.  I'll take a look the next chance that I get.  It probably won't be until next week.

**Comment by khurrumsaleem** [comment]
@scopatz i believe that the this fork (https://github.com/scopatz/xsgen) has solved the problem with 

#ctx['_fuel_nucs'] = _mat_to_nucs(rc.fuel_material[valid_nucs])
        curr_fuel = self.libs['fuel']['material'][-1][valid_nucs]
        ctx['_fuel_nucs'] = _mat_to_nucs(curr_fuel[valid_nucs])      

i came up with a solution of similar sorts and then later saw your directory.

**Comment by FlanFlanagan** [comment]
Are we good to close this issue?

**Comment by scopatz** [comment]
I believe that we are.  Please reopen if you want @khurrumsaleem
